version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Cursor_HW20_HennadiiBulava
      MYSQL_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  web:
    build: ..
    ports:
      - "1248:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Cursor_HW20_HennadiiBulava?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - db
volumes:
  db_data: